# Generated by Django 2.2.13 on 2020-06-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='test_api',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
